version: '3.5'

services:
    Prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - /root/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - /root/Prometheus/rules.yml:/etc/prometheus/rules.yml
        


    Alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        ports:
            - 9093:9093
        volumes:
            - /root/Prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      
       
    Nginx:
        image: nginx
        container_name: nginx
        ports:
            - 8080:80
    
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports: 
            - "3000:3000"
        command: grafana-cli plugins install alexanderzobnin-zabbix-app
        restart: unless-stopped
        

